spring:
  application:
    name: SpringBoot4Demo

  datasource:
    url: jdbc:postgresql://localhost:5432/slink
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
