spring:
  ai:

    model:
      embedding: vertex-ai-embedding

    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: vector_store
        use-tls: false
        initialize-schema: true

    chat:
      client:
        enabled: false

      memory:
        repository:
          jdbc:
            initialize-schema: ALWAYS


    ollama:
      base-url: http://192.168.214.178:11434
      chat:
        options:
          model: deepseek-r1:8b

    vertex:
      ai:
        gemini:
          project -id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
        embedding:
          project-id: ${GEMINI_PROJECT_ID}
          location: us-central1
          text:
            options:
              model: text-embedding-004
              auto-truncate: true
#          chat:
#            options:
#              model: gemini-2.5-pro



  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG



